# -*- coding: utf-8 -*-
"""tugas_akhir_judul2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zH34TA9-QewyWIlsegEgKKKoCwtWncKw
"""

def insertion_sort(arr, n):
  for i in range(1, n):
    temp = arr[i]
    j = i - 1
    while j >= 0 and arr[j] > temp:
      arr[j + 1] = arr[j]
      j -= 1
    arr[j + 1] = temp

def main():
  try:
    n = int(input("Masukkan jumlah elemen: "))
  except ValueError:
    print("Input tidak valid!")
    return
  arr = []
  print("Masukkan lama nya waktu tidur:")
  for i in range(n):
    while True:
      try:
        nilai = int(input())
        arr.append(nilai)
        break
      except ValueError:
        print("Input tidak valid, silakan masukkan angka!")
  print(f"Array sebelum diurutkan: {arr}")
  insertion_sort(arr, n)
  print("Array setelah diurutkan (Insertion Sort):", end=" ")
  for i in range(n):
    print(arr[i], end=" ")
  print()

if __name__ == "__main__":
  main()