# -*- coding: utf-8 -*-
"""tugas_akhir_judul1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M6p3JSJF0lUAxrdSLNH1dbq1Lc2uWjDp
"""

class MenuMakanan:
    def __init__(self, nama):
        self.nama = nama
        self.next = None
        self.prev = None

class DaftarMenu:
    def __init__(self):
        self.head = None
        self.current = None

    def tambah_makanan(self, nama):
        new_menu = MenuMakanan(nama)
        if not self.head:
            self.head = new_menu
            self.current = new_menu
        else:
            temp = self.head
            while temp.next:
                temp = temp.next
            temp.next = new_menu
            new_menu.prev = temp

    def hapus_makanan(self, nama):
        temp = self.head
        while temp:
            if temp.nama == nama:
                if temp.prev:
                    temp.prev.next = temp.next
                else:
                    self.head = temp.next

                if temp.next:
                    temp.next.prev = temp.prev

                if self.current == temp:
                    self.current = temp.next or temp.prev

                print("Makanan dihapus")
                return
            temp = temp.next
        print("Makanan tidak ditemukan")

    def tampilkan_menu(self):
        temp = self.head
        if not temp:
            print("Menu kosong")
            return
        while temp:
            print(temp.nama, end=" <-> ")
            temp = temp.next
        print("None")

    def lihat_makanan(self):
        if self.current:
            print("Makanan saat ini:", self.current.nama)
        else:
            print("Tidak ada menu")

    def menu_selanjutnya(self):
        if self.current and self.current.next:
            self.current = self.current.next
            self.lihat_makanan()
        else:
            print("Sudah di menu terakhir")

    def menu_sebelumnya(self):
        if self.current and self.current.prev:
            self.current = self.current.prev
            self.lihat_makanan()
        else:
            print("Sudah di menu pertama")


menu = DaftarMenu()

while True:
    print("\n=== MENU MAKANAN ===")
    print("1. Tambah Makanan")
    print("2. Hapus Makanan")
    print("3. Tampilkan Menu")
    print("4. Lihat Makanan Sekarang")
    print("5. Menu Selanjutnya")
    print("6. Menu Sebelumnya")
    print("0. Keluar")

    pilih = input("Pilih menu: ")

    if pilih == "1":
        nama = input("Masukkan nama makanan: ")
        menu.tambah_makanan(nama)

    elif pilih == "2":
        nama = input("Masukkan makanan yang ingin dihapus: ")
        menu.hapus_makanan(nama)

    elif pilih == "3":
        menu.tampilkan_menu()

    elif pilih == "4":
        menu.lihat_makanan()

    elif pilih == "5":
        menu.menu_selanjutnya()

    elif pilih == "6":
        menu.menu_sebelumnya()

    elif pilih == "0":
        print("Keluar dari program")
        break

    else:
        print("Pilihan tidak valid")